#!/bin/sh
# overwrites local DB with recent dump of remote
# usage: script/db_pull wlc2013
# defaults to staging

set -e

REMOTE=${1:-production}
DATABASE_NAME=foodlobby_development

DUMP_NAME=tmp/$REMOTE.dump
MY_DIR=`dirname $0`

echo dumping latest $REMOTE db into local $DATABASE_NAME

heroku pgbackups:capture -e --remote $REMOTE
curl -o $DUMP_NAME `heroku pgbackups:url --remote $REMOTE`

$MY_DIR/db_load $APP
